import streamlit as st
import pandas as pd
import yfinance as yf
import numpy as np
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

# ==========================================
# 1. CONFIGURATION & STYLING
# ==========================================
st.set_page_config(page_title="DCF Valuation Tool", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
body { font-family: 'Inter', sans-serif; background: linear-gradient(135deg, #1e1e2f 0%, #2a2a3e 100%); color: #f0f2f6; }

/* Cards & Containers */
.glass-card { background: rgba(255,255,255,0.05); border-radius: 12px; padding: 20px; border: 1px solid rgba(255,255,255,0.1); margin-bottom: 20px; }
.val-card { background: rgba(255,255,255,0.03); border-radius: 12px; padding: 24px; border: 1px solid rgba(255,255,255,0.08); height: 100%; transition: transform 0.2s; }
.val-card:hover { transform: translateY(-3px); }

/* Typography & Accents */
.val-label { font-size: 11px; font-weight: 700; opacity: 0.5; letter-spacing: 1px; text-transform: uppercase; }
.val-price { font-size: 42px; font-weight: 700; margin: 4px 0 16px 0; color: #fff; }
.val-title { font-size: 18px; font-weight: 600; margin-bottom: 4px; color: #fff; }
.val-sub { font-size: 12px; opacity: 0.6; margin-bottom: 20px; }
.status-under { color: #4ade80; font-weight: 700; }
.status-over { color: #f87171; font-weight: 700; }
.text-blue { color: #60a5fa; }
.text-purple { color: #a78bfa; }
.text-green { color: #34d399; }
.border-purple { border-left: 5px solid #8b5cf6; }
.border-green { border-left: 5px solid #10b981; }

div[data-testid="stExpander"] { background-color: rgba(255,255,255,0.02); border-radius: 12px; }
</style>
""", unsafe_allow_html=True)

st.markdown('<h1 style="text-align:center; margin-bottom: 30px;">DCF Valuation Tool</h1>', unsafe_allow_html=True)

# ==========================================
# 2. PDF GENERATION ENGINE (Python)
# ==========================================
def create_pdf(ticker, date, price, int_val, upside, wacc, ltg, exit_m, c_curr):
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, f"Valuation Report: {ticker}")
    
    # Header Info
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 80, f"Date: {date}")
    c.drawString(50, height - 100, "Method: Discounted Cash Flow (DCF)")

    # Divider
    c.line(50, height - 110, width - 50, height - 110)

    # --- RESULTS SECTION ---
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 150, "Valuation Results")

    c.setFont("Helvetica", 14)
    c.drawString(50, height - 180, f"Current Price: {c_curr}{price:,.2f}")
    c.drawString(50, height - 200, f"Intrinsic Value: {c_curr}{int_val:,.2f}")
    
    # Color logic for text (Manual in PDF)
    status = "UNDERVALUED" if upside >= 0 else "OVERVALUED"
    c.drawString(50, height - 220, f"Upside: {upside:+.1%} ({status})")

    # --- ASSUMPTIONS SECTION ---
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 270, "Key Assumptions")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 300, f"WACC: {wacc:.1%}")
    c.drawString(50, height - 320, f"Terminal Growth (Gordon): {ltg:.1%}")
    c.drawString(50, height - 340, f"Exit Multiple (EBITDA): {exit_m}x")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Python Streamlit DCF Tool")
    
    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

# ==========================================
# 3. DATA ENGINE
# ==========================================
@st.cache_data(ttl=3600, show_spinner=False)
def get_yahoo_data(ticker):
    try:
        tk = yf.Ticker(ticker)
        try: price = tk.fast_info.last_price
        except: 
            hist = tk.history(period="1d")
            price = hist['Close'].iloc[-1] if not hist.empty else 0.0

        try: shares = tk.info.get('sharesOutstanding')
        except: shares = None
        if not shares: 
            try: shares = tk.fast_info.shares_outstanding
            except: pass
        if not shares: shares = 1e9
        shares = shares / 1e9 

        industry = tk.info.get('industry', 'Unknown')
        price_curr = tk.info.get('currency', 'USD')
        fin_curr = tk.info.get('financialCurrency', price_curr)
        
        fx_rate = 1.0
        fx_msg = ""
        if price_curr != fin_curr:
            pair = f"{fin_curr}{price_curr}=X"
            try:
                fx = yf.Ticker(pair)
                rate = fx.fast_info.last_price
                if rate:
                    fx_rate = rate
                    fx_msg = f"Converted {fin_curr} to {price_curr} (Rate: {fx_rate:.3f})"
            except:
                fx_msg = f"⚠️ FX Error: Could not fetch rate for {pair}."

        inc = tk.income_stmt
        bs = tk.balance_sheet
        cf = tk.cashflow
        if inc.empty: raise ValueError("No financial statements found.")

        def get_val(df, keys):
            if df.empty: return 0.0
            for k in keys:
                if k in df.index: return df.loc[k].iloc[0]
            return 0.0

        data = {}
        factor = fx_rate / 1e9 
        data['Revenue'] = get_val(inc, ['Total Revenue', 'Total Net Sales']) * factor
        data['EBIT']    = get_val(inc, ['Operating Income', 'EBIT']) * factor
        data['Depreciation'] = get_val(cf, ['Depreciation And Amortization']) * factor
        if data['Depreciation'] == 0: data['Depreciation'] = get_val(inc, ['Reconciled Depreciation']) * factor
        data['Capex'] = abs(get_val(cf, ['Capital Expenditure', 'Capital Expenditures'])) * factor
        data['Debt'] = get_val(bs, ['Total Debt', 'Long Term Debt']) * factor
        data['Cash'] = get_val(bs, ['Cash And Cash Equivalents']) * factor
        
        return data, price, shares, fx_msg, price_curr, industry
    except Exception as e:
        return None, 0.0, 1.0, str(e), "USD", "Unknown"

# ==========================================
# 4. UI: INPUTS
# ==========================================
c_tick, c_space, c_pdf = st.columns([.50, 5, 0.55], vertical_alignment="bottom")

with c_tick:
    ticker = st.text_input("Ticker", "NVDA").upper()

# PLACEHOLDER for the PDF button (It will be populated at the end of the script)
pdf_spot = c_pdf.empty()

if 'y0' not in st.session_state:
    st.session_state.y0 = {k:0.0 for k in ['Revenue','EBIT','Depreciation','Capex','Debt','Cash']}

if 'reset_key' not in st.session_state:
    st.session_state.reset_key = 0

curr_symbol = "$"
industry_name = "Unknown"

if ticker:
    with st.spinner(f"Analysing {ticker}..."):
        if 'last_ticker' not in st.session_state or st.session_state.last_ticker != ticker:
            d, cur_price, shares_def, fx_msg, currency, ind_name = get_yahoo_data(ticker)
            if d:
                st.session_state.y0 = d
                st.session_state.last_price = cur_price
                st.session_state.last_shares = shares_def
                st.session_state.last_ticker = ticker
                st.session_state.fx_msg = fx_msg
                st.session_state.currency = currency
                st.session_state.industry = ind_name
                st.session_state.reset_key += 1
            else:
                st.error(f"Error: {fx_msg}")
                cur_price, shares_def = 0.0, 1.0
                st.session_state.fx_msg = ""
                st.session_state.currency = "USD"
                st.session_state.industry = "Unknown"
        else:
            cur_price = st.session_state.last_price
            shares_def = st.session_state.last_shares
            fx_info = st.session_state.get('fx_msg', "")
            curr_code = st.session_state.get('currency', 'USD')
            industry_name = st.session_state.get('industry', 'Unknown')
            curr_symbol = "€" if curr_code == 'EUR' else "£" if curr_code == 'GBP' else "¥" if curr_code in ['CNY','JPY'] else "$"

    if st.session_state.get('fx_msg'):
        st.info(f"💱 {st.session_state.fx_msg}")

r_in = st.session_state.y0['Revenue']
e_in = st.session_state.y0['EBIT']
d_in = st.session_state.y0['Depreciation']
c_in = st.session_state.y0['Capex']

# ==========================================
# 5. SCENARIO & DRIVERS (SIDEBAR)
# ==========================================
with st.sidebar:
    st.header("Configuration")
    
    scenario = st.selectbox("Scenario Mode", ["Base Case", "Bull Case 🚀", "Bear Case 🐻"])
    
    if "Bull" in scenario:
        mult_g, mult_m, mult_e = 1.2, 1.1, 1.15
        st.success("Growth +20%, Margin +10%")
    elif "Bear" in scenario:
        mult_g, mult_m, mult_e = 0.7, 0.8, 0.8
        st.warning("Growth -30%, Margin -20%")
    else:
        mult_g, mult_m, mult_e = 1.0, 1.0, 1.0

    st.divider()
    st.header("Assumptions")
    wacc_in = st.number_input("WACC %", value=9.0, step=0.1, format="%.1f")
    wacc = wacc_in / 100
    
    st.markdown("### Balance Sheet (B)")
    debt_in = st.number_input("Total Debt", value=st.session_state.y0['Debt'], format="%.3f")
    cash_in = st.number_input("Total Cash", value=st.session_state.y0['Cash'], format="%.3f")
    shares_in = st.number_input("Shares (B)", value=shares_def, format="%.3f")

    st.divider()
    st.subheader("Drivers")
    st.caption(f"Detected Industry: {industry_name}")
    
    current_margin = (e_in / r_in) if r_in > 0 else 0.0
    
    if current_margin > 0.30: def_growth, def_mult = 15.0, 25.0
    elif current_margin < 0.10: def_growth, def_mult = 3.0, 8.0
    else: def_growth, def_mult = 5.0, 12.0
    
    g_rev_in = st.number_input("Revenue Growth %", value=def_growth * mult_g, step=0.5, format="%.1f")
    g_rev = g_rev_in / 100
    
    m_def = (current_margin * 100)
    margin_tgt_in = st.number_input("EBIT Margin %", value=float(f"{m_def * mult_m:.1f}"), step=0.5, format="%.1f")
    margin_tgt = margin_tgt_in / 100
    
    tax_rate = st.number_input("Tax Rate %", value=21.0, step=1.0, format="%.1f") / 100
    
    ltg_in = st.number_input("Terminal Growth %", value=2.5, step=0.1, format="%.1f")
    ltg = ltg_in / 100
    
    exit_mult = st.number_input("Exit Multiple (x)", value=def_mult * mult_e, step=0.5, format="%.1f")

# ==========================================
# 6. CALCULATION FUNCTIONS
# ==========================================
def calculate_dcf_value(r_0, e_0, d_0, c_0, g, m, t, w, l, em, debt, cash, shares, years=5):
    if w <= l: l = w - 0.005 
    
    cap_r = c_0/r_0 if r_0 else 0
    dep_r = d_0/r_0 if r_0 else 0
    nwc_r = 0.02
    
    fcf_pv_sum = 0.0
    prev_rev = r_0
    
    last_fcf = 0.0
    last_ebitda = 0.0
    
    for y in range(1, years + 1):
        rev = prev_rev * (1 + g)
        ebit = rev * m
        nopat = ebit * (1 - t)
        da = rev * dep_r
        capex = rev * cap_r
        dnwc = (rev - prev_rev) * nwc_r
        
        fcff = nopat + da - capex - dnwc
        pv = fcff * ((1 + w)**-y)
        fcf_pv_sum += pv
        
        prev_rev = rev
        if y == years:
            last_fcf = fcff
            last_ebitda = ebit + da

    tv_g = last_fcf * (1 + l) / (w - l)
    pv_tv_g = tv_g * ((1 + w)**-years)
    
    tv_e = last_ebitda * em
    pv_tv_e = tv_e * ((1 + w)**-years)
    
    eq_g = (fcf_pv_sum + pv_tv_g) - (debt - cash)
    eq_e = (fcf_pv_sum + pv_tv_e) - (debt - cash)
    
    price_g = eq_g / shares if shares > 0 else 0
    price_e = eq_e / shares if shares > 0 else 0
    
    return (price_g + price_e) / 2

years_range = range(1, 6)
base_data = []
safe_ltg = ltg if ltg < wacc else (wacc - 0.005)

if r_in > 0:
    nopat0 = e_in * (1 - tax_rate)
    fcff0 = nopat0 + d_in - c_in
    base_data.append({'Year': 0, 'Revenue': r_in, 'EBIT': e_in, 'NOPAT': nopat0, 'D&A': d_in, 'Capex': c_in, 'FCFF': fcff0, 'PV': 0.0})

    cap_r, dep_r, nwc_r = c_in/r_in, d_in/r_in, 0.02
    prev_rev = r_in

    for y in years_range:
        rev = prev_rev * (1 + g_rev)
        ebit = rev * margin_tgt
        nopat = ebit * (1 - tax_rate)
        da, capex = rev * dep_r, rev * cap_r
        dnwc = (rev - prev_rev) * nwc_r
        fcff = nopat + da - capex - dnwc
        pv = fcff * ((1 + wacc)**-y)
        base_data.append({'Year':y,'Revenue':rev,'EBIT':ebit,'NOPAT':nopat,'D&A':da,'Capex':capex,'FCFF':fcff,'PV':pv})
        prev_rev = rev
else:
    for y in range(0, 6): base_data.append({'Year':y,'Revenue':0.0,'EBIT':0.0,'NOPAT':0.0,'D&A':0.0,'Capex':0.0,'FCFF':0.0,'PV':0.0})

df_base = pd.DataFrame(base_data).set_index('Year')

# ==========================================
# 7. INTERACTIVE TABLE
# ==========================================
st.divider()

c_title, c_space, c_toggle, c_reset = st.columns([7, 2.5, 0.7, 0.7], vertical_alignment="bottom")

with c_title:
    st.subheader(f"Projected Free Cash Flow (Millions {curr_symbol})")

with c_toggle:
    is_unlocked = st.toggle("Unlock", value=False)

with c_reset:
    if st.button("↺ Reset", use_container_width=True):
        st.session_state.reset_key += 1
        st.rerun()

df_display = (df_base * 1000).T
df_display.columns = [f"Year {y}" for y in range(6)]
df_formatted = df_display.applymap(lambda x: f"{x:,.2f}")
disabled_cols = df_formatted.columns if not is_unlocked else []

edited_df = st.data_editor(
    df_formatted,
    use_container_width=True,
    disabled=disabled_cols,
    key=f"editor_{st.session_state.reset_key}"
)

# ==========================================
# 8. MAIN VALUATION LOGIC
# ==========================================
try:
    def clean_num(val):
        if isinstance(val, (int, float)): return val
        return float(str(val).replace(',', '').replace('$', '').replace('€','').replace('£','').replace('¥',''))

    fcf_stream = []
    
    for y in years_range:
        col_name = f"Year {y}"
        rev_edit = clean_num(edited_df.loc['Revenue', col_name]) / 1000
        ebit_edit = clean_num(edited_df.loc['EBIT', col_name]) / 1000
        da_edit = clean_num(edited_df.loc['D&A', col_name]) / 1000
        capex_edit = clean_num(edited_df.loc['Capex', col_name]) / 1000
        
        prev_col = f"Year {y-1}"
        rev_prev = clean_num(edited_df.loc['Revenue', prev_col]) / 1000
        dnwc = (rev_edit - rev_prev) * 0.02
        
        nopat = ebit_edit * (1 - tax_rate)
        fcff_recalc = nopat + da_edit - capex_edit - dnwc
        
        pv_recalc = fcff_recalc * ((1 + wacc)**-y)
        fcf_stream.append(pv_recalc)
        
        if y == 5:
            fcf5_final = fcff_recalc
            ebitda5_final = ebit_edit + da_edit

    sum_pv_final = sum(fcf_stream)

    tv_g = fcf5_final * (1+safe_ltg)/(wacc-safe_ltg)
    pv_tv_g = tv_g * ((1+wacc)**-5)
    
    tv_e = ebitda5_final * exit_mult
    pv_tv_e = tv_e * ((1+wacc)**-5)

    ev_g = sum_pv_final + pv_tv_g
    eq_g = ev_g - (debt_in - cash_in)
    p_g = (eq_g / shares_in) if shares_in > 0 else 0

    ev_e = sum_pv_final + pv_tv_e
    eq_e = ev_e - (debt_in - cash_in)
    p_e = (eq_e / shares_in) if shares_in > 0 else 0

    avg_int = (p_g + p_e) / 2
    if cur_price > 0: mos_pct = (avg_int - cur_price) / cur_price
    else: mos_pct = 0.0

except Exception as e:
    p_g, p_e, avg_int, mos_pct = 0,0,0,0
    ev_g, ev_e = 0,0

# ==========================================
# 9. RESULTS & DOWNLOAD
# ==========================================
st.divider()

if cur_price > 0 and r_in > 0:
    s_col = "status-under" if mos_pct >= 0 else "status-over"
    s_txt = "UNDERVALUED" if mos_pct >= 0 else "OVERVALUED"
    st.markdown(f"""
    <div class="glass-card" style="display:flex; justify-content: space-around; align-items: center;">
        <div style="text-align:center;"><div class="val-label">CURRENT PRICE</div><div class="val-price">{curr_symbol}{cur_price:,.2f}</div></div>
        <div style="text-align:center;">
            <div class="val-label">INTRINSIC VALUE</div>
            <div class="val-price text-blue" style="margin-bottom: 5px;">{curr_symbol}{avg_int:,.2f}</div>
            <div style="font-size: 10px; opacity: 0.6; font-weight: 400;">(Average Implied Value)</div>
        </div>
        <div style="text-align:center;"><div class="val-label">UPSIDE</div><div class="val-price {s_col}">{mos_pct:+.1%}</div><div class="{s_col}">{s_txt}</div></div>
    </div>
    """, unsafe_allow_html=True)

    # >>> GENERATE PDF & ACTIVATE BUTTON <<<
    pdf_bytes = create_pdf(
        ticker, 
        pd.Timestamp.now().strftime('%Y-%m-%d'),
        cur_price, 
        avg_int, 
        mos_pct, 
        wacc, 
        safe_ltg, 
        exit_mult, 
        curr_symbol
    )
    
    # We populate the empty container we made at the top
    pdf_spot.download_button(
        label="📄 Download PDF",
        data=pdf_bytes,
        file_name=f"{ticker}_Valuation_Report.pdf",
        mime="application/pdf",
    )

st.markdown("<br>", unsafe_allow_html=True)

c_g, c_e = st.columns(2)
def make_bridge(pv_fcf, pv_tv, ev, debt, cash, eq):
    return pd.DataFrame({
        "Component": ["PV of 5y Cash Flows", "PV of Terminal", "Enterprise Value", "Less: Net Debt", "Equity Value"],
        "Value": [pv_fcf, pv_tv, ev, debt-cash, eq]
    }).set_index("Component")

bridge_format = f"{curr_symbol}{{:,.2f}}B"

with c_g:
    st.markdown(f"""<div class="val-card border-purple"><div class="val-title">Gordon Growth 🌊</div><div class="val-sub">Based on {safe_ltg:.1%} long-term growth</div><div class="val-label">IMPLIED SHARE PRICE</div><div class="val-price text-purple">{curr_symbol}{p_g:,.2f}</div><div class="val-ev"><span>Enterprise Value</span><strong>{curr_symbol}{ev_g:,.2f}B</strong></div></div>""", unsafe_allow_html=True)
    st.markdown("##### Bridge (Gordon)")
    st.dataframe(make_bridge(sum_pv_final, pv_tv_g, ev_g, debt_in, cash_in, ev_g-(debt_in-cash_in)).style.format(bridge_format), use_container_width=True)

with c_e:
    st.markdown(f"""<div class="val-card border-green"><div class="val-title">Exit Multiple 💼</div><div class="val-sub">Based on {exit_mult}x EBITDA multiple</div><div class="val-label">IMPLIED SHARE PRICE</div><div class="val-price text-green">{curr_symbol}{p_e:,.2f}</div><div class="val-ev"><span>Enterprise Value</span><strong>{curr_symbol}{ev_e:,.2f}B</strong></div></div>""", unsafe_allow_html=True)
    st.markdown("##### Bridge (Multiple)")
    st.dataframe(make_bridge(sum_pv_final, pv_tv_e, ev_e, debt_in, cash_in, ev_e-(debt_in-cash_in)).style.format(bridge_format), use_container_width=True)

# ==========================================
# 10. SENSITIVITY ANALYSIS
# ==========================================
st.markdown("<br><hr><br>", unsafe_allow_html=True)
st.subheader("Sensitivity Analysis 🎯")
st.caption("Implied Share Price based on WACC vs. Terminal Growth Rate")

wacc_range = [wacc - 0.01, wacc - 0.005, wacc, wacc + 0.005, wacc + 0.01]
ltg_range = [ltg - 0.005, ltg - 0.0025, ltg, ltg + 0.0025, ltg + 0.005]

sens_data = {}
for t_g in ltg_range:
    col_data = []
    for w_r in wacc_range:
        val = calculate_dcf_value(r_in, e_in, d_in, c_in, g_rev, margin_tgt, tax_rate, w_r, t_g, exit_mult, debt_in, cash_in, shares_in)
        col_data.append(val)
    sens_data[f"{t_g:.2%}"] = col_data

df_sens = pd.DataFrame(sens_data, index=[f"{w:.1%}" for w in wacc_range])
df_sens.index.name = "WACC"
df_sens.columns.name = "Terminal Growth"

def style_sens(val):
    color = '#2a2a3e' 
    if val > cur_price * 1.1: color = '#105234' 
    elif val < cur_price * 0.9: color = '#4a151b' 
    return f'background-color: {color}; color: white; border: 1px solid #444;'

st.dataframe(df_sens.style.format(f"{curr_symbol}{{:,.2f}}").applymap(style_sens), use_container_width=True)
st.info("💡 **How to read:** Green cells indicate the stock is undervalued even with these assumptions. Red indicates overvaluation.")
